// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file greet.proto (package greet, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file greet.proto.
 */
export const file_greet: GenFile = /*@__PURE__*/
  fileDesc("CgtncmVldC5wcm90bxIFZ3JlZXQiHAoMSGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiHQoKSGVsbG9SZXBseRIPCgdtZXNzYWdlGAEgASgJMj0KB0dyZWV0ZXISMgoIU2F5SGVsbG8SEy5ncmVldC5IZWxsb1JlcXVlc3QaES5ncmVldC5IZWxsb1JlcGx5QjCqAi1OZXdpbmZvc29mdC5DaGluZXNlSGlzdG9yeS5TZXJ2ZXIuU2VydmljZUJhc2ViBnByb3RvMw");

/**
 * The request message containing the user's name.
 *
 * @generated from message greet.HelloRequest
 */
export type HelloRequest = Message<"greet.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message greet.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_greet, 0);

/**
 * The response message containing the greetings.
 *
 * @generated from message greet.HelloReply
 */
export type HelloReply = Message<"greet.HelloReply"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message greet.HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export const HelloReplySchema: GenMessage<HelloReply> = /*@__PURE__*/
  messageDesc(file_greet, 1);

/**
 * The greeting service definition.
 *
 * @generated from service greet.Greeter
 */
export const Greeter: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc greet.Greeter.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_greet, 0);

