// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file greet.proto (package chinesehistory, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file greet.proto.
 */
export const file_greet: GenFile = /*@__PURE__*/
  fileDesc("CgtncmVldC5wcm90bxIOY2hpbmVzZWhpc3RvcnkiHAoMSGVsbG9SZXF1ZXN0EgwKBG5hbWUYASABKAkiHQoKSGVsbG9SZXBseRIPCgdtZXNzYWdlGAEgASgJMk8KB0dyZWV0ZXISRAoIU2F5SGVsbG8SHC5jaGluZXNlaGlzdG9yeS5IZWxsb1JlcXVlc3QaGi5jaGluZXNlaGlzdG9yeS5IZWxsb1JlcGx5QjCqAi1OZXdpbmZvc29mdC5DaGluZXNlSGlzdG9yeS5TZXJ2ZXIuU2VydmljZUJhc2ViBnByb3RvMw");

/**
 * The request message containing the user's name.
 *
 * @generated from message chinesehistory.HelloRequest
 */
export type HelloRequest = Message<"chinesehistory.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message chinesehistory.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_greet, 0);

/**
 * The response message containing the greetings.
 *
 * @generated from message chinesehistory.HelloReply
 */
export type HelloReply = Message<"chinesehistory.HelloReply"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message chinesehistory.HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export const HelloReplySchema: GenMessage<HelloReply> = /*@__PURE__*/
  messageDesc(file_greet, 1);

/**
 * The greeting service definition.
 *
 * @generated from service chinesehistory.Greeter
 */
export const Greeter: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc chinesehistory.Greeter.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_greet, 0);

