// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file layer.proto (package chinesehistory, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file layer.proto.
 */
export const file_layer: GenFile = /*@__PURE__*/
  fileDesc("CgtsYXllci5wcm90bxIOY2hpbmVzZWhpc3RvcnkimAEKDkhpc3RvcmljYWxEYXRlEjMKDWNhbGVuZGFyX3R5cGUYASABKA4yHC5jaGluZXNlaGlzdG9yeS5DYWxlbmRhclR5cGUSDAoEeWVhchgCIAEoBRINCgVtb250aBgDIAEoBRILCgNkYXkYBCABKAUSFQoNaXNfbGVhcF9tb250aBgFIAEoCBIQCghlcmFfbmFtZRgGIAEoCSJuChBHZXRMYXllcnNSZXF1ZXN0Ei0KBXN0YXJ0GAEgASgLMh4uY2hpbmVzZWhpc3RvcnkuSGlzdG9yaWNhbERhdGUSKwoDZW5kGAIgASgLMh4uY2hpbmVzZWhpc3RvcnkuSGlzdG9yaWNhbERhdGUimQEKCUxheWVySXRlbRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEicKBHR5cGUYAyABKA4yGS5jaGluZXNlaGlzdG9yeS5MYXllclR5cGUSFQoNZ2VvbWV0cnlfanNvbhgEIAEoCRISCgpzdGFydF9kYXRlGAUgASgJEhAKCGVuZF9kYXRlGAYgASgJEgwKBHRhZ3MYByADKAkiPQoRR2V0TGF5ZXJzUmVzcG9uc2USKAoFaXRlbXMYASADKAsyGS5jaGluZXNlaGlzdG9yeS5MYXllckl0ZW0qRwoJTGF5ZXJUeXBlEgsKB1VOS05PV04QABIICgRDSVRZEAESCQoFRVZFTlQQAhINCglURVJSSVRPUlkQAxIJCgVST1VURRAEKjEKDENhbGVuZGFyVHlwZRINCglHUkVHT1JJQU4QABIJCgVMVU5BUhABEgcKA0VSQRACMmAKDExheWVyU2VydmljZRJQCglHZXRMYXllcnMSIC5jaGluZXNlaGlzdG9yeS5HZXRMYXllcnNSZXF1ZXN0GiEuY2hpbmVzZWhpc3RvcnkuR2V0TGF5ZXJzUmVzcG9uc2VCMKoCLU5ld2luZm9zb2Z0LkNoaW5lc2VIaXN0b3J5LlNlcnZlci5TZXJ2aWNlQmFzZWIGcHJvdG8z");

/**
 * 历史日期结构（新版本）
 *
 * @generated from message chinesehistory.HistoricalDate
 */
export type HistoricalDate = Message<"chinesehistory.HistoricalDate"> & {
  /**
   * 纪年类型（GREGORIAN, LUNAR, ERA）
   *
   * @generated from field: chinesehistory.CalendarType calendar_type = 1;
   */
  calendarType: CalendarType;

  /**
   * 年号第几年或公历年，负数表示公元前
   *
   * @generated from field: int32 year = 2;
   */
  year: number;

  /**
   * 月份（1~12）
   *
   * @generated from field: int32 month = 3;
   */
  month: number;

  /**
   * 日（1~31）
   *
   * @generated from field: int32 day = 4;
   */
  day: number;

  /**
   * 是否闰月，仅对农历有效
   *
   * @generated from field: bool is_leap_month = 5;
   */
  isLeapMonth: boolean;

  /**
   * 年号（如"贞观"，用于 ERA 类型）
   *
   * @generated from field: string era_name = 6;
   */
  eraName: string;
};

/**
 * Describes the message chinesehistory.HistoricalDate.
 * Use `create(HistoricalDateSchema)` to create a new message.
 */
export const HistoricalDateSchema: GenMessage<HistoricalDate> = /*@__PURE__*/
  messageDesc(file_layer, 0);

/**
 * 请求结构：按历史时间范围获取图层
 *
 * @generated from message chinesehistory.GetLayersRequest
 */
export type GetLayersRequest = Message<"chinesehistory.GetLayersRequest"> & {
  /**
   * 起始时间
   *
   * @generated from field: chinesehistory.HistoricalDate start = 1;
   */
  start?: HistoricalDate;

  /**
   * 结束时间
   *
   * @generated from field: chinesehistory.HistoricalDate end = 2;
   */
  end?: HistoricalDate;
};

/**
 * Describes the message chinesehistory.GetLayersRequest.
 * Use `create(GetLayersRequestSchema)` to create a new message.
 */
export const GetLayersRequestSchema: GenMessage<GetLayersRequest> = /*@__PURE__*/
  messageDesc(file_layer, 1);

/**
 * 图层元素结构
 *
 * @generated from message chinesehistory.LayerItem
 */
export type LayerItem = Message<"chinesehistory.LayerItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: chinesehistory.LayerType type = 3;
   */
  type: LayerType;

  /**
   * @generated from field: string geometry_json = 4;
   */
  geometryJson: string;

  /**
   * @generated from field: string start_date = 5;
   */
  startDate: string;

  /**
   * @generated from field: string end_date = 6;
   */
  endDate: string;

  /**
   * @generated from field: repeated string tags = 7;
   */
  tags: string[];
};

/**
 * Describes the message chinesehistory.LayerItem.
 * Use `create(LayerItemSchema)` to create a new message.
 */
export const LayerItemSchema: GenMessage<LayerItem> = /*@__PURE__*/
  messageDesc(file_layer, 2);

/**
 * 返回结构
 *
 * @generated from message chinesehistory.GetLayersResponse
 */
export type GetLayersResponse = Message<"chinesehistory.GetLayersResponse"> & {
  /**
   * @generated from field: repeated chinesehistory.LayerItem items = 1;
   */
  items: LayerItem[];
};

/**
 * Describes the message chinesehistory.GetLayersResponse.
 * Use `create(GetLayersResponseSchema)` to create a new message.
 */
export const GetLayersResponseSchema: GenMessage<GetLayersResponse> = /*@__PURE__*/
  messageDesc(file_layer, 3);

/**
 * 枚举：图层类型
 *
 * @generated from enum chinesehistory.LayerType
 */
export enum LayerType {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: CITY = 1;
   */
  CITY = 1,

  /**
   * @generated from enum value: EVENT = 2;
   */
  EVENT = 2,

  /**
   * @generated from enum value: TERRITORY = 3;
   */
  TERRITORY = 3,

  /**
   * @generated from enum value: ROUTE = 4;
   */
  ROUTE = 4,
}

/**
 * Describes the enum chinesehistory.LayerType.
 */
export const LayerTypeSchema: GenEnum<LayerType> = /*@__PURE__*/
  enumDesc(file_layer, 0);

/**
 * 枚举：历史纪年类型
 *
 * @generated from enum chinesehistory.CalendarType
 */
export enum CalendarType {
  /**
   * 公元纪年
   *
   * @generated from enum value: GREGORIAN = 0;
   */
  GREGORIAN = 0,

  /**
   * 农历
   *
   * @generated from enum value: LUNAR = 1;
   */
  LUNAR = 1,

  /**
   * 年号
   *
   * @generated from enum value: ERA = 2;
   */
  ERA = 2,
}

/**
 * Describes the enum chinesehistory.CalendarType.
 */
export const CalendarTypeSchema: GenEnum<CalendarType> = /*@__PURE__*/
  enumDesc(file_layer, 1);

/**
 * @generated from service chinesehistory.LayerService
 */
export const LayerService: GenService<{
  /**
   * @generated from rpc chinesehistory.LayerService.GetLayers
   */
  getLayers: {
    methodKind: "unary";
    input: typeof GetLayersRequestSchema;
    output: typeof GetLayersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_layer, 0);

