// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file war.proto (package chinesehistory, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { GregorianDate } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file war.proto.
 */
export const file_war: GenFile = /*@__PURE__*/
  fileDesc("Cgl3YXIucHJvdG8SDmNoaW5lc2VoaXN0b3J5Iv8BCgNXYXISCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIxCgpzdGFydF9kYXRlGAQgASgLMh0uY2hpbmVzZWhpc3RvcnkuR3JlZ29yaWFuRGF0ZRIvCghlbmRfZGF0ZRgFIAEoCzIdLmNoaW5lc2VoaXN0b3J5LkdyZWdvcmlhbkRhdGUSFQoNZ2VvbWV0cnlfanNvbhgGIAEoCRIpCgh3YXJfdHlwZRgHIAEoDjIXLmNoaW5lc2VoaXN0b3J5LldhclR5cGUSDAoEdGFncxgIIAMoCRIVCg1zZWFyY2hfdmFsdWVzGAkgAygJIjQKD0dldFdhcnNSZXNwb25zZRIhCgR3YXJzGAEgAygLMhMuY2hpbmVzZWhpc3RvcnkuV2FyIjIKDkdldFdhclJlc3BvbnNlEiAKA3dhchgBIAEoCzITLmNoaW5lc2VoaXN0b3J5LldhciIjChFHZXRXYXJCeUlkUmVxdWVzdBIOCgZ3YXJfaWQYASABKAkiTAoRU2VhcmNoV2Fyc1JlcXVlc3QSDAoEbmFtZRgBIAEoCRIpCgh3YXJfdHlwZRgCIAEoDjIXLmNoaW5lc2VoaXN0b3J5LldhclR5cGUiNwoSU2VhcmNoV2Fyc1Jlc3BvbnNlEiEKBHdhcnMYASADKAsyEy5jaGluZXNlaGlzdG9yeS5XYXIiqAEKFkdldFdhcnNCeVBlcmlvZFJlcXVlc3QSMQoKc3RhcnRfZGF0ZRgBIAEoCzIdLmNoaW5lc2VoaXN0b3J5LkdyZWdvcmlhbkRhdGUSLwoIZW5kX2RhdGUYAiABKAsyHS5jaGluZXNlaGlzdG9yeS5HcmVnb3JpYW5EYXRlEioKCXdhcl90eXBlcxgDIAMoDjIXLmNoaW5lc2VoaXN0b3J5LldhclR5cGUiPAoXR2V0V2Fyc0J5UGVyaW9kUmVzcG9uc2USIQoEd2FycxgBIAMoCzITLmNoaW5lc2VoaXN0b3J5LldhciqtAQoHV2FyVHlwZRIPCgtVTktOT1dOX1dBUhAAEg0KCUNJVklMX1dBUhABEg8KC0ZPUkVJR05fV0FSEAISDQoJUkVCRUxMSU9OEAMSFAoQUEVBU0FOVF9VUFJJU0lORxAEEhIKDlNVQ0NFU1NJT05fV0FSEAUSEwoPVEVSUklUT1JJQUxfV0FSEAYSEQoNREVGRU5TSVZFX1dBUhAHEhAKDENPTlFVRVNUX1dBUhAIMuMCCgpXYXJTZXJ2aWNlEksKB0dldFdhcnMSHy5jaGluZXNlaGlzdG9yeS5HZXRXYXJzUmVzcG9uc2UaHy5jaGluZXNlaGlzdG9yeS5HZXRXYXJzUmVzcG9uc2USTwoKR2V0V2FyQnlJZBIhLmNoaW5lc2VoaXN0b3J5LkdldFdhckJ5SWRSZXF1ZXN0Gh4uY2hpbmVzZWhpc3RvcnkuR2V0V2FyUmVzcG9uc2USUwoKU2VhcmNoV2FycxIhLmNoaW5lc2VoaXN0b3J5LlNlYXJjaFdhcnNSZXF1ZXN0GiIuY2hpbmVzZWhpc3RvcnkuU2VhcmNoV2Fyc1Jlc3BvbnNlEmIKD0dldFdhcnNCeVBlcmlvZBImLmNoaW5lc2VoaXN0b3J5LkdldFdhcnNCeVBlcmlvZFJlcXVlc3QaJy5jaGluZXNlaGlzdG9yeS5HZXRXYXJzQnlQZXJpb2RSZXNwb25zZUIwqgItTmV3aW5mb3NvZnQuQ2hpbmVzZUhpc3RvcnkuU2VydmVyLlNlcnZpY2VCYXNlYgZwcm90bzM", [file_common]);

/**
 * 战争实体 - 历史上的军事冲突
 *
 * @generated from message chinesehistory.War
 */
export type War = Message<"chinesehistory.War"> & {
  /**
   * 战争唯一标识符
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 战争名称（如"城濮之战"）
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * 战争描述
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * 开始日期
   *
   * @generated from field: chinesehistory.GregorianDate start_date = 4;
   */
  startDate?: GregorianDate;

  /**
   * 结束日期
   *
   * @generated from field: chinesehistory.GregorianDate end_date = 5;
   */
  endDate?: GregorianDate;

  /**
   * 地理位置JSON（GeoJSON格式）
   *
   * @generated from field: string geometry_json = 6;
   */
  geometryJson: string;

  /**
   * 战争类型
   *
   * @generated from field: chinesehistory.WarType war_type = 7;
   */
  warType: WarType;

  /**
   * 标签
   *
   * @generated from field: repeated string tags = 8;
   */
  tags: string[];

  /**
   * 搜索辅助工具，例如拼音、声母
   *
   * @generated from field: repeated string search_values = 9;
   */
  searchValues: string[];
};

/**
 * Describes the message chinesehistory.War.
 * Use `create(WarSchema)` to create a new message.
 */
export const WarSchema: GenMessage<War> = /*@__PURE__*/
  messageDesc(file_war, 0);

/**
 * 获取所有战争响应
 *
 * @generated from message chinesehistory.GetWarsResponse
 */
export type GetWarsResponse = Message<"chinesehistory.GetWarsResponse"> & {
  /**
   * @generated from field: repeated chinesehistory.War wars = 1;
   */
  wars: War[];
};

/**
 * Describes the message chinesehistory.GetWarsResponse.
 * Use `create(GetWarsResponseSchema)` to create a new message.
 */
export const GetWarsResponseSchema: GenMessage<GetWarsResponse> = /*@__PURE__*/
  messageDesc(file_war, 1);

/**
 * 获取单个战争响应
 *
 * @generated from message chinesehistory.GetWarResponse
 */
export type GetWarResponse = Message<"chinesehistory.GetWarResponse"> & {
  /**
   * @generated from field: chinesehistory.War war = 1;
   */
  war?: War;
};

/**
 * Describes the message chinesehistory.GetWarResponse.
 * Use `create(GetWarResponseSchema)` to create a new message.
 */
export const GetWarResponseSchema: GenMessage<GetWarResponse> = /*@__PURE__*/
  messageDesc(file_war, 2);

/**
 * 获取战争请求
 *
 * @generated from message chinesehistory.GetWarByIdRequest
 */
export type GetWarByIdRequest = Message<"chinesehistory.GetWarByIdRequest"> & {
  /**
   * 战争ID
   *
   * @generated from field: string war_id = 1;
   */
  warId: string;
};

/**
 * Describes the message chinesehistory.GetWarByIdRequest.
 * Use `create(GetWarByIdRequestSchema)` to create a new message.
 */
export const GetWarByIdRequestSchema: GenMessage<GetWarByIdRequest> = /*@__PURE__*/
  messageDesc(file_war, 3);

/**
 * 根据名称搜索战争请求
 *
 * @generated from message chinesehistory.SearchWarsRequest
 */
export type SearchWarsRequest = Message<"chinesehistory.SearchWarsRequest"> & {
  /**
   * 战争名称（支持模糊搜索）
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * 战争类型（可选）
   *
   * @generated from field: chinesehistory.WarType war_type = 2;
   */
  warType: WarType;
};

/**
 * Describes the message chinesehistory.SearchWarsRequest.
 * Use `create(SearchWarsRequestSchema)` to create a new message.
 */
export const SearchWarsRequestSchema: GenMessage<SearchWarsRequest> = /*@__PURE__*/
  messageDesc(file_war, 4);

/**
 * 搜索战争响应
 *
 * @generated from message chinesehistory.SearchWarsResponse
 */
export type SearchWarsResponse = Message<"chinesehistory.SearchWarsResponse"> & {
  /**
   * @generated from field: repeated chinesehistory.War wars = 1;
   */
  wars: War[];
};

/**
 * Describes the message chinesehistory.SearchWarsResponse.
 * Use `create(SearchWarsResponseSchema)` to create a new message.
 */
export const SearchWarsResponseSchema: GenMessage<SearchWarsResponse> = /*@__PURE__*/
  messageDesc(file_war, 5);

/**
 * 获取特定时期的战争列表请求
 *
 * @generated from message chinesehistory.GetWarsByPeriodRequest
 */
export type GetWarsByPeriodRequest = Message<"chinesehistory.GetWarsByPeriodRequest"> & {
  /**
   * 开始日期
   *
   * @generated from field: chinesehistory.GregorianDate start_date = 1;
   */
  startDate?: GregorianDate;

  /**
   * 结束日期
   *
   * @generated from field: chinesehistory.GregorianDate end_date = 2;
   */
  endDate?: GregorianDate;

  /**
   * 战争类型过滤（可选）
   *
   * @generated from field: repeated chinesehistory.WarType war_types = 3;
   */
  warTypes: WarType[];
};

/**
 * Describes the message chinesehistory.GetWarsByPeriodRequest.
 * Use `create(GetWarsByPeriodRequestSchema)` to create a new message.
 */
export const GetWarsByPeriodRequestSchema: GenMessage<GetWarsByPeriodRequest> = /*@__PURE__*/
  messageDesc(file_war, 6);

/**
 * 获取特定时期的战争列表响应
 *
 * @generated from message chinesehistory.GetWarsByPeriodResponse
 */
export type GetWarsByPeriodResponse = Message<"chinesehistory.GetWarsByPeriodResponse"> & {
  /**
   * 该时期的战争列表
   *
   * @generated from field: repeated chinesehistory.War wars = 1;
   */
  wars: War[];
};

/**
 * Describes the message chinesehistory.GetWarsByPeriodResponse.
 * Use `create(GetWarsByPeriodResponseSchema)` to create a new message.
 */
export const GetWarsByPeriodResponseSchema: GenMessage<GetWarsByPeriodResponse> = /*@__PURE__*/
  messageDesc(file_war, 7);

/**
 * 战争类型枚举
 *
 * @generated from enum chinesehistory.WarType
 */
export enum WarType {
  /**
   * 未知
   *
   * @generated from enum value: UNKNOWN_WAR = 0;
   */
  UNKNOWN_WAR = 0,

  /**
   * 内战
   *
   * @generated from enum value: CIVIL_WAR = 1;
   */
  CIVIL_WAR = 1,

  /**
   * 对外战争
   *
   * @generated from enum value: FOREIGN_WAR = 2;
   */
  FOREIGN_WAR = 2,

  /**
   * 叛乱
   *
   * @generated from enum value: REBELLION = 3;
   */
  REBELLION = 3,

  /**
   * 农民起义
   *
   * @generated from enum value: PEASANT_UPRISING = 4;
   */
  PEASANT_UPRISING = 4,

  /**
   * 王位继承战争
   *
   * @generated from enum value: SUCCESSION_WAR = 5;
   */
  SUCCESSION_WAR = 5,

  /**
   * 领土争夺战
   *
   * @generated from enum value: TERRITORIAL_WAR = 6;
   */
  TERRITORIAL_WAR = 6,

  /**
   * 防御战争
   *
   * @generated from enum value: DEFENSIVE_WAR = 7;
   */
  DEFENSIVE_WAR = 7,

  /**
   * 征服战争
   *
   * @generated from enum value: CONQUEST_WAR = 8;
   */
  CONQUEST_WAR = 8,
}

/**
 * Describes the enum chinesehistory.WarType.
 */
export const WarTypeSchema: GenEnum<WarType> = /*@__PURE__*/
  enumDesc(file_war, 0);

/**
 * @generated from service chinesehistory.WarService
 */
export const WarService: GenService<{
  /**
   * @generated from rpc chinesehistory.WarService.GetWars
   */
  getWars: {
    methodKind: "unary";
    input: typeof GetWarsResponseSchema;
    output: typeof GetWarsResponseSchema;
  },
  /**
   * @generated from rpc chinesehistory.WarService.GetWarById
   */
  getWarById: {
    methodKind: "unary";
    input: typeof GetWarByIdRequestSchema;
    output: typeof GetWarResponseSchema;
  },
  /**
   * @generated from rpc chinesehistory.WarService.SearchWars
   */
  searchWars: {
    methodKind: "unary";
    input: typeof SearchWarsRequestSchema;
    output: typeof SearchWarsResponseSchema;
  },
  /**
   * @generated from rpc chinesehistory.WarService.GetWarsByPeriod
   */
  getWarsByPeriod: {
    methodKind: "unary";
    input: typeof GetWarsByPeriodRequestSchema;
    output: typeof GetWarsByPeriodResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_war, 0);

