// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file war.proto (package chinesehistory, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { BatchOperationResponseSchema, GregorianDate } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file war.proto.
 */
export const file_war: GenFile = /*@__PURE__*/
  fileDesc("Cgl3YXIucHJvdG8SDmNoaW5lc2VoaXN0b3J5Iv8BCgNXYXISCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIxCgpzdGFydF9kYXRlGAQgASgLMh0uY2hpbmVzZWhpc3RvcnkuR3JlZ29yaWFuRGF0ZRIvCghlbmRfZGF0ZRgFIAEoCzIdLmNoaW5lc2VoaXN0b3J5LkdyZWdvcmlhbkRhdGUSFQoNZ2VvbWV0cnlfanNvbhgGIAEoCRIpCgh3YXJfdHlwZRgHIAEoDjIXLmNoaW5lc2VoaXN0b3J5LldhclR5cGUSDAoEdGFncxgIIAMoCRIVCg1zZWFyY2hfdmFsdWVzGAkgAygJIjQKD0dldFdhcnNSZXNwb25zZRIhCgR3YXJzGAEgAygLMhMuY2hpbmVzZWhpc3RvcnkuV2FyIhAKDkdldFdhcnNSZXF1ZXN0IvgBCg9GaW5kV2Fyc1JlcXVlc3QSDgoGd2FyX2lkGAEgASgJEgwKBG5hbWUYAiABKAkSKQoId2FyX3R5cGUYAyABKA4yFy5jaGluZXNlaGlzdG9yeS5XYXJUeXBlEjEKCnN0YXJ0X2RhdGUYBCABKAsyHS5jaGluZXNlaGlzdG9yeS5HcmVnb3JpYW5EYXRlEi8KCGVuZF9kYXRlGAUgASgLMh0uY2hpbmVzZWhpc3RvcnkuR3JlZ29yaWFuRGF0ZRIqCgl3YXJfdHlwZXMYBiADKA4yFy5jaGluZXNlaGlzdG9yeS5XYXJUeXBlEgwKBHRhZ3MYByADKAkiNgoRVXBzZXJ0V2Fyc1JlcXVlc3QSIQoEd2FycxgBIAMoCzITLmNoaW5lc2VoaXN0b3J5LldhciIkChFEZWxldGVXYXJzUmVxdWVzdBIPCgd3YXJfaWRzGAEgAygJKq0BCgdXYXJUeXBlEg8KC1VOS05PV05fV0FSEAASDQoJQ0lWSUxfV0FSEAESDwoLRk9SRUlHTl9XQVIQAhINCglSRUJFTExJT04QAxIUChBQRUFTQU5UX1VQUklTSU5HEAQSEgoOU1VDQ0VTU0lPTl9XQVIQBRITCg9URVJSSVRPUklBTF9XQVIQBhIRCg1ERUZFTlNJVkVfV0FSEAcSEAoMQ09OUVVFU1RfV0FSEAgy2AIKCldhclNlcnZpY2USSgoHR2V0V2FycxIeLmNoaW5lc2VoaXN0b3J5LkdldFdhcnNSZXF1ZXN0Gh8uY2hpbmVzZWhpc3RvcnkuR2V0V2Fyc1Jlc3BvbnNlEkwKCEZpbmRXYXJzEh8uY2hpbmVzZWhpc3RvcnkuRmluZFdhcnNSZXF1ZXN0Gh8uY2hpbmVzZWhpc3RvcnkuR2V0V2Fyc1Jlc3BvbnNlElcKClVwc2VydFdhcnMSIS5jaGluZXNlaGlzdG9yeS5VcHNlcnRXYXJzUmVxdWVzdBomLmNoaW5lc2VoaXN0b3J5LkJhdGNoT3BlcmF0aW9uUmVzcG9uc2USVwoKRGVsZXRlV2FycxIhLmNoaW5lc2VoaXN0b3J5LkRlbGV0ZVdhcnNSZXF1ZXN0GiYuY2hpbmVzZWhpc3RvcnkuQmF0Y2hPcGVyYXRpb25SZXNwb25zZUIwqgItTmV3aW5mb3NvZnQuQ2hpbmVzZUhpc3RvcnkuU2VydmVyLlNlcnZpY2VCYXNlYgZwcm90bzM", [file_common]);

/**
 * 战争实体 - 历史上的军事冲突
 *
 * @generated from message chinesehistory.War
 */
export type War = Message<"chinesehistory.War"> & {
  /**
   * 战争唯一标识符
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 战争名称（如"城濮之战"）
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * 战争描述
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * 开始日期
   *
   * @generated from field: chinesehistory.GregorianDate start_date = 4;
   */
  startDate?: GregorianDate;

  /**
   * 结束日期
   *
   * @generated from field: chinesehistory.GregorianDate end_date = 5;
   */
  endDate?: GregorianDate;

  /**
   * 地理位置JSON（GeoJSON格式）
   *
   * @generated from field: string geometry_json = 6;
   */
  geometryJson: string;

  /**
   * 战争类型
   *
   * @generated from field: chinesehistory.WarType war_type = 7;
   */
  warType: WarType;

  /**
   * 标签
   *
   * @generated from field: repeated string tags = 8;
   */
  tags: string[];

  /**
   * 搜索辅助工具，例如拼音、声母
   *
   * @generated from field: repeated string search_values = 9;
   */
  searchValues: string[];
};

/**
 * Describes the message chinesehistory.War.
 * Use `create(WarSchema)` to create a new message.
 */
export const WarSchema: GenMessage<War> = /*@__PURE__*/
  messageDesc(file_war, 0);

/**
 * 获取多个战争响应（统一用于GetWars和FindWars）
 *
 * @generated from message chinesehistory.GetWarsResponse
 */
export type GetWarsResponse = Message<"chinesehistory.GetWarsResponse"> & {
  /**
   * @generated from field: repeated chinesehistory.War wars = 1;
   */
  wars: War[];
};

/**
 * Describes the message chinesehistory.GetWarsResponse.
 * Use `create(GetWarsResponseSchema)` to create a new message.
 */
export const GetWarsResponseSchema: GenMessage<GetWarsResponse> = /*@__PURE__*/
  messageDesc(file_war, 1);

/**
 * 获取战争请求（无查询条件）
 *
 * 空请求，获取所有战争
 *
 * @generated from message chinesehistory.GetWarsRequest
 */
export type GetWarsRequest = Message<"chinesehistory.GetWarsRequest"> & {
};

/**
 * Describes the message chinesehistory.GetWarsRequest.
 * Use `create(GetWarsRequestSchema)` to create a new message.
 */
export const GetWarsRequestSchema: GenMessage<GetWarsRequest> = /*@__PURE__*/
  messageDesc(file_war, 2);

/**
 * 查找战争请求（包含所有可能的查询条件）
 *
 * @generated from message chinesehistory.FindWarsRequest
 */
export type FindWarsRequest = Message<"chinesehistory.FindWarsRequest"> & {
  /**
   * 战争ID（可选）
   *
   * @generated from field: string war_id = 1;
   */
  warId: string;

  /**
   * 战争名称（支持模糊搜索）（可选）
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * 战争类型（可选）
   *
   * @generated from field: chinesehistory.WarType war_type = 3;
   */
  warType: WarType;

  /**
   * 开始日期（可选）
   *
   * @generated from field: chinesehistory.GregorianDate start_date = 4;
   */
  startDate?: GregorianDate;

  /**
   * 结束日期（可选）
   *
   * @generated from field: chinesehistory.GregorianDate end_date = 5;
   */
  endDate?: GregorianDate;

  /**
   * 战争类型过滤（可选）
   *
   * @generated from field: repeated chinesehistory.WarType war_types = 6;
   */
  warTypes: WarType[];

  /**
   * 标签过滤（可选）
   *
   * @generated from field: repeated string tags = 7;
   */
  tags: string[];
};

/**
 * Describes the message chinesehistory.FindWarsRequest.
 * Use `create(FindWarsRequestSchema)` to create a new message.
 */
export const FindWarsRequestSchema: GenMessage<FindWarsRequest> = /*@__PURE__*/
  messageDesc(file_war, 3);

/**
 * 批量战争操作请求
 *
 * @generated from message chinesehistory.UpsertWarsRequest
 */
export type UpsertWarsRequest = Message<"chinesehistory.UpsertWarsRequest"> & {
  /**
   * 要插入或更新的战争列表
   *
   * @generated from field: repeated chinesehistory.War wars = 1;
   */
  wars: War[];
};

/**
 * Describes the message chinesehistory.UpsertWarsRequest.
 * Use `create(UpsertWarsRequestSchema)` to create a new message.
 */
export const UpsertWarsRequestSchema: GenMessage<UpsertWarsRequest> = /*@__PURE__*/
  messageDesc(file_war, 4);

/**
 * 批量删除战争请求
 *
 * @generated from message chinesehistory.DeleteWarsRequest
 */
export type DeleteWarsRequest = Message<"chinesehistory.DeleteWarsRequest"> & {
  /**
   * 要删除的战争ID列表
   *
   * @generated from field: repeated string war_ids = 1;
   */
  warIds: string[];
};

/**
 * Describes the message chinesehistory.DeleteWarsRequest.
 * Use `create(DeleteWarsRequestSchema)` to create a new message.
 */
export const DeleteWarsRequestSchema: GenMessage<DeleteWarsRequest> = /*@__PURE__*/
  messageDesc(file_war, 5);

/**
 * 战争类型枚举
 *
 * @generated from enum chinesehistory.WarType
 */
export enum WarType {
  /**
   * 未知
   *
   * @generated from enum value: UNKNOWN_WAR = 0;
   */
  UNKNOWN_WAR = 0,

  /**
   * 内战
   *
   * @generated from enum value: CIVIL_WAR = 1;
   */
  CIVIL_WAR = 1,

  /**
   * 对外战争
   *
   * @generated from enum value: FOREIGN_WAR = 2;
   */
  FOREIGN_WAR = 2,

  /**
   * 叛乱
   *
   * @generated from enum value: REBELLION = 3;
   */
  REBELLION = 3,

  /**
   * 农民起义
   *
   * @generated from enum value: PEASANT_UPRISING = 4;
   */
  PEASANT_UPRISING = 4,

  /**
   * 王位继承战争
   *
   * @generated from enum value: SUCCESSION_WAR = 5;
   */
  SUCCESSION_WAR = 5,

  /**
   * 领土争夺战
   *
   * @generated from enum value: TERRITORIAL_WAR = 6;
   */
  TERRITORIAL_WAR = 6,

  /**
   * 防御战争
   *
   * @generated from enum value: DEFENSIVE_WAR = 7;
   */
  DEFENSIVE_WAR = 7,

  /**
   * 征服战争
   *
   * @generated from enum value: CONQUEST_WAR = 8;
   */
  CONQUEST_WAR = 8,
}

/**
 * Describes the enum chinesehistory.WarType.
 */
export const WarTypeSchema: GenEnum<WarType> = /*@__PURE__*/
  enumDesc(file_war, 0);

/**
 * @generated from service chinesehistory.WarService
 */
export const WarService: GenService<{
  /**
   * ============== 查询操作 ==============
   * 获取所有战争
   *
   * @generated from rpc chinesehistory.WarService.GetWars
   */
  getWars: {
    methodKind: "unary";
    input: typeof GetWarsRequestSchema;
    output: typeof GetWarsResponseSchema;
  },
  /**
   * 查找战争（根据条件）
   *
   * @generated from rpc chinesehistory.WarService.FindWars
   */
  findWars: {
    methodKind: "unary";
    input: typeof FindWarsRequestSchema;
    output: typeof GetWarsResponseSchema;
  },
  /**
   * ============== 批量CRUD操作 ==============
   * 批量插入或更新战争
   *
   * @generated from rpc chinesehistory.WarService.UpsertWars
   */
  upsertWars: {
    methodKind: "unary";
    input: typeof UpsertWarsRequestSchema;
    output: typeof BatchOperationResponseSchema;
  },
  /**
   * 批量删除战争
   *
   * @generated from rpc chinesehistory.WarService.DeleteWars
   */
  deleteWars: {
    methodKind: "unary";
    input: typeof DeleteWarsRequestSchema;
    output: typeof BatchOperationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_war, 0);

