// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file src/protos/greet.proto (package greet, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file src/protos/greet.proto.
 */
export const file_src_protos_greet: GenFile = /*@__PURE__*/
  fileDesc("ChZzcmMvcHJvdG9zL2dyZWV0LnByb3RvEgVncmVldCIcCgxIZWxsb1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIdCgpIZWxsb1JlcGx5Eg8KB21lc3NhZ2UYASABKAkyPQoHR3JlZXRlchIyCghTYXlIZWxsbxITLmdyZWV0LkhlbGxvUmVxdWVzdBoRLmdyZWV0LkhlbGxvUmVwbHlCMKoCLU5ld2luZm9zb2Z0LkNoaW5lc2VIaXN0b3J5LlNlcnZlci5TZXJ2aWNlQmFzZWIGcHJvdG8z");

/**
 * The request message containing the user's name.
 *
 * @generated from message greet.HelloRequest
 */
export type HelloRequest = Message<"greet.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message greet.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_src_protos_greet, 0);

/**
 * The response message containing the greetings.
 *
 * @generated from message greet.HelloReply
 */
export type HelloReply = Message<"greet.HelloReply"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message greet.HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export const HelloReplySchema: GenMessage<HelloReply> = /*@__PURE__*/
  messageDesc(file_src_protos_greet, 1);

/**
 * The greeting service definition.
 *
 * @generated from service greet.Greeter
 */
export const Greeter: GenService<{
  /**
   * Sends a greeting
   *
   * @generated from rpc greet.Greeter.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_src_protos_greet, 0);

